In [2]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")
print("\n--- Task 1: Array Creation Shortcuts ---")
print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150,160]])
print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5))
print("\n--- Task 4: Aggregation Functions ---")
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])
print("\n--- Task 5: Reshaping and Flattening ---")
arr5_1 = np.arange(24)
print("\n--- Task 6: Broadcasting ---")
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])
print("\n--- Task 7: Copying vs. Viewing Arrays ---")
original_arr7 = np.array([1, 2, 3, 4, 5])
print("\n--- Task 8: Stacking and Splitting Arrays ---")
arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])
print("\n--- Task 9: Sorting and Searching ---")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])





--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [ 1  2  3  4  5  6  7  8  9 10]
arr1_2:
 [[0. 0. 0.]
 [0. 0. 0.]]
arr1_3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arr1_4 (first 2 rows):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

--- Task 2: Indexing and Slicing with Arrays ---

--- Task 3: Conditional Operations ---

--- Task 4: Aggregation Functions ---

--- Task 5: Reshaping and Flattening ---

--- Task 6: Broadcasting ---

--- Task 7: Copying vs. Viewing Arrays ---

--- Task 8: Stacking and Splitting Arrays ---

--- Task 9: Sorting and Searching ---
