In [2]:
a = np.arange(6).reshape(2, 3)
print('Array a:\n', a)
print('shape :', a.shape)
print('ndim  :', a.ndim)
print('dtype :', a.dtype)


Array a:
 [[0 1 2]
 [3 4 5]]
shape : (2, 3)
ndim  : 2
dtype : int64


In [3]:
print('Column index 1 :', a[:, 1])
print('Row index 0    :', a[0, :])
print('Elements > 2   :', a[a > 2])

Column index 1 : [1 4]
Row index 0    : [0 1 2]
Elements > 2   : [3 4 5]


In [4]:
row = np.array([10, 20, 30])
print('a + row (row added to every row of a):\n', a + row)

a + row (row added to every row of a):
 [[10 21 32]
 [13 24 35]]


In [7]:
 print('Column-wise sum  (axis=0):', a.sum(axis=0))
print('Row-wise sum     (axis=1):', a.sum(axis=1))
print('Row-wise mean    (axis=1):', a.mean(axis=1))
print('Index of max per column  :', a.argmax(axis=0))


Column-wise sum  (axis=0): [3 5 7]
Row-wise sum     (axis=1): [ 3 12]
Row-wise mean    (axis=1): [1. 4.]
Index of max per column  : [1 1 1]


In [8]:
M = np.arange(1, 13).reshape(3, 4)
N = np.arange(1, 9).reshape(4, 2)
print('M:\n', M)
print('N:\n', N)

M:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
N:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
